### Instructions: 
"This week we are adding datetime types to the mix, as well as using everything else we've done so far.

The attached data set is climate data from Denver International Airport for the first half of February, 2019.

Drop any columns you deem unnecessary.
Set the date column as the index of the DataFrame.
Create an "Elapsed Time" column that shows the amount of time since the first observation.
Format the "Elapsed Time" column into some easily-readable form. For example, after two hours, the column should NOT read 7200.
Do all the things we've already been doing -- format the headings, deal with missing values, etc.
Perform analysis with the tools we've looked at so far. Keep in mind that the data may have to be grouped to be meaningful (average temp per day may be more useful than average for the whole two weeks, for example). Justify your analysis choices.
Deliverable is your Jupyter notebook. Remember, just attach the notebook. Don't change the file extension and don't zip it."

### Importing packages, data, and cleaning dataframe:

In [1]:
# Here are packages we will import and will use throughout the lab(mostly). We will discuss them more while they are in use.
# Additionally we will import datetime later on

import os
import requests
import pandas as pd
import numpy as np
import re

In [2]:
#loading .csv into data frame and seperating columns by ','
df = pd.read_csv('1618421.csv', sep=',')

In [3]:
#checking df
df

,STATION,STATION_NAME,ELEVATION,LATITUDE,LONGITUDE,DATE,REPORTTPYE,HOURLYSKYCONDITIONS,HOURLYVISIBILITY,HOURLYPRSENTWEATHERTYPE,...,MonthlyMaxSeaLevelPressureTime,MonthlyMinSeaLevelPressureValue,MonthlyMinSeaLevelPressureDate,MonthlyMinSeaLevelPressureTime,MonthlyTotalHeatingDegreeDays,MonthlyTotalCoolingDegreeDays,MonthlyDeptFromNormalHeatingDD,MonthlyDeptFromNormalCoolingDD,MonthlyTotalSeasonToDateHeatingDD,MonthlyTotalSeasonToDateCoolingDD
0,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 00:37,FM-16,SCT:04 9,7.00,NaN,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
1,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 00:46,FM-16,BKN:07 9 BKN:07 180,9.00,NaN,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
2,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 00:53,FM-15,BKN:07 9 BKN:07 180,10.00,NaN,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
3,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 01:05,FM-16,OVC:08 10,10.00,NaN,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
4,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 01:33,FM-16,BKN:07 9 BKN:07 180,10.00,NaN,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1706,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 21:53,FM-15,FEW:02 30 OVC:08 100,10.00,NaN,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
1707,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 22:53,FM-15,FEW:02 30 OVC:08 90,10.00,NaN,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
1708,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 23:00,FM-12,26,NaN,NaN,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
1709,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 23:53,FM-15,FEW:02 20 OVC:08 110,10.00,NaN,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
1710,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 23:59,SOD,NaN,NaN,NaN,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN

## dropping unnecessary columns

In [4]:
#here is a good look at the df. We will compare this ouptput as well as the one above and below to determine what columns we can drop 
df.describe()

,ELEVATION,LATITUDE,LONGITUDE,HOURLYWETBULBTEMPF,HOURLYWETBULBTEMPC,HOURLYDewPointTempF,HOURLYDewPointTempC,HOURLYRelativeHumidity,HOURLYWindGustSpeed,HOURLYStationPressure,...,MonthlyMaxSeaLevelPressureTime,MonthlyMinSeaLevelPressureValue,MonthlyMinSeaLevelPressureDate,MonthlyMinSeaLevelPressureTime,MonthlyTotalHeatingDegreeDays,MonthlyTotalCoolingDegreeDays,MonthlyDeptFromNormalHeatingDD,MonthlyDeptFromNormalCoolingDD,MonthlyTotalSeasonToDateHeatingDD,MonthlyTotalSeasonToDateCoolingDD
count,1.711000e+03,1.711000e+03,1.711000e+03,1666.000000,1666.000000,1666.000000,1666.000000,1666.000000,97.000000,1666.000000,...,1711.0,0.0,1711.0,1711.0,1.0,1.0,1.0,1.0,0.0,0.0
mean,1.650200e+03,3.983280e+01,-1.046575e+02,24.853541,-3.966507,16.673469,-8.511885,63.340336,31.938144,24.513313,...,-9999.0,NaN,-9999.0,-9999.0,1016.0,0.0,-47.0,0.0,NaN,NaN
std,2.342634e-11,1.485468e-12,1.023481e-12,9.879766,5.465728,8.380600,4.656388,22.671277,7.549578,0.176896,...,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
min,1.650200e+03,3.983280e+01,-1.046575e+02,-10.000000,-23.600000,-14.000000,-25.600000,11.000000,16.000000,24.030000,...,-9999.0,NaN,-9999.0,-9999.0,1016.0,0.0,-47.0,0.0,NaN,NaN
25%,1.650200e+03,3.983280e+01,-1.046575e+02,19.000000,-7.000000,12.000000,-11.100000,45.000000,28.000000,24.390000,...,-9999.0,NaN,-9999.0,-9999.0,1016.0,0.0,-47.0,0.0,NaN,NaN
50%,1.650200e+03,3.983280e+01,-1.046575e+02,26.000000,-3.200000,18.000000,-7.800000,63.000000,31.000000,24.550000,...,-9999.0,NaN,-9999.0,-9999.0,1016.0,0.0,-47.0,0.0,NaN,NaN
75%,1.650200e+03,3.983280e+01,-1.046575e+02,32.000000,0.100000,22.000000,-5.600000,85.000000,37.000000,24.640000,...,-9999.0,NaN,-9999.0,-9999.0,1016.0,0.0,-47.0,0.0,NaN,NaN
max,1.650200e+03,3.983280e+01,-1.046575e+02,46.000000,7.700000,34.000000,1.100000,100.000000,54.000000,24.950000,...,-9999.0,NaN,-9999.0,-9999.0,1016.0,0.0,-47.0,0.0,NaN,NaN

In [5]:
#checking object types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1711 entries, 0 to 1710
Data columns (total 90 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   STATION                            1711 non-null   object
 1   STATION_NAME                       1711 non-null   object
 2   ELEVATION                          1711 non-null   float64
 3   LATITUDE                           1711 non-null   float64
 4   LONGITUDE                          1711 non-null   float64
 5   DATE                               1711 non-null   object
 6   REPORTTPYE                         1711 non-null   object
 7   HOURLYSKYCONDITIONS                1417 non-null   object
 8   HOURLYVISIBILITY                   1307 non-null   object
 9   HOURLYPRSENTWEATHERTYPE            350 non-null    object
 10  HOURLYDRYBULBTEMPF                 1666 non-null   object
 11  HOURLYDRYBULBTEMPC                 1666 non-null   object
 12  HOURLYWETBULBTEMPF                 1666 non-null   float64
 13  HOURLYWETBULBTEMPC                 1666 non-null   float64
 14  HOURLYDewPointTempF                1666 non-null   float64
 15  HOURLYDewPointTempC                1666 non-null   float64
 16  HOURLYRelativeHumidity             1666 non-null   float64
 17  HOURLYWindSpeed                    1666 non-null   object
 18  HOURLYWindDirection                1664 non-null   object
 19  HOURLYWindGustSpeed                97 non-null     float64
 20  HOURLYStationPressure              1666 non-null   float64
 21  HOURLYPressureTendency             686 non-null    float64
 22  HOURLYPressureChange               354 non-null    float64
 23  HOURLYSeaLevelPressure             1440 non-null   float64
 24  HOURLYPrecip                       1198 non-null   object
 25  HOURLYAltimeterSetting             1308 non-null   float64
 26  DAILYMaximumDryBulbTemp            180 non-null    object
 27  DAILYMinimumDryBulbTemp            180 non-null    object
 28  DAILYAverageDryBulbTemp            180 non-null    object
 29  DAILYDeptFromNormalAverageTemp     180 non-null    object
 30  DAILYAverageRelativeHumidity       0 non-null      float64
 31  DAILYAverageDewPointTemp           0 non-null      float64
 32  DAILYAverageWetBulbTemp            0 non-null      float64
 33  DAILYHeatingDegreeDays             180 non-null    object
 34  DAILYCoolingDegreeDays             180 non-null    object
 35  DAILYSunrise                       1711 non-null   int64
 36  DAILYSunset                        1711 non-null   int64
 37  DAILYWeather                       15 non-null     object
 38  DAILYPrecip                        61 non-null     object
 39  DAILYSnowfall                      45 non-null     object
 40  DAILYSnowDepth                     45 non-null     object
 41  DAILYAverageStationPressure        45 non-null     float64
 42  DAILYAverageSeaLevelPressure       0 non-null      float64
 43  DAILYAverageWindSpeed              44 non-null     float64
 44  DAILYPeakWindSpeed                 45 non-null     object
 45  PeakWindDirection                  45 non-null     object
 46  DAILYSustainedWindSpeed            45 non-null     float64
 47  DAILYSustainedWindDirection        45 non-null     float64
 48  MonthlyMaximumTemp                 1 non-null      float64
 49  MonthlyMinimumTemp                 1 non-null      float64
 50  MonthlyMeanTemp                    1 non-null      float64
 51  MonthlyAverageRH                   0 non-null      float64
 52  MonthlyDewpointTemp                0 non-null      float64
 53  MonthlyWetBulbTemp                 0 non-null      float64
 54  MonthlyAvgHeatingDegreeDays        0 non-null      float64
 55  MonthlyAvgCoolingDegreeDays        0 non-null      float64
 56  MonthlyStationPressure             1 non-null      float64
 57  MonthlySeaLevelPressure            1 non-null      float64
 58  MonthlyAverageWindSpeed            0 non-null      float64
 59  MonthlyTotalSnowfall               11 non-null     object
 60  MonthlyDeptFromNormalMaximumTemp   1 non-null      float64
 61  MonthlyDeptFromNormalMinimumTemp   1 non-null      float64
 62  MonthlyDeptFromNormalAverageTemp   1 non-null      float64
 63  MonthlyDeptFromNormalPrecip        1 non-null      object
 64  MonthlyTotalLiquidPrecip           1 non-null      object
 65  MonthlyGreatestPrecip              0 non-null      float64
 66  MonthlyGreatestPrecipDate          0 non-null      float64
 67  MonthlyGreatestSnowfall            0 non-null      float64
 68  MonthlyGreatestSnowfallDate        0 non-null      float64
 69  MonthlyGreatestSnowDepth           0 non-null      float64
 70  MonthlyGreatestSnowDepthDate       0 non-null      float64
 71  MonthlyDaysWithGT90Temp            1 non-null      float64
 72  MonthlyDaysWithLT32Temp            1 non-null      float64
 73  MonthlyDaysWithGT32Temp            1 non-null      float64
 74  MonthlyDaysWithLT0Temp             1 non-null      float64
 75  MonthlyDaysWithGT001Precip         0 non-null      float64
 76  MonthlyDaysWithGT010Precip         0 non-null      float64
 77  MonthlyDaysWithGT1Snow             0 non-null      float64
 78  MonthlyMaxSeaLevelPressureValue    0 non-null      float64
 79  MonthlyMaxSeaLevelPressureDate     1711 non-null   int64
 80  MonthlyMaxSeaLevelPressureTime     1711 non-null   int64
 81  MonthlyMinSeaLevelPressureValue    0 non-null      float64
 82  MonthlyMinSeaLevelPressureDate     1711 non-null   int64
 83  MonthlyMinSeaLevelPressureTime     1711 non-null   int64
 84  MonthlyTotalHeatingDegreeDays      1 non-null      float64
 85  MonthlyTotalCoolingDegreeDays      1 non-null      float64
 86  MonthlyDeptFromNormalHeatingDD     1 non-null      float64
 87  MonthlyDeptFromNormalCoolingDD     1 non-null      float64
 88  MonthlyTotalSeasonToDateHeatingDD  0 non-null      float64
 89  MonthlyTotalSeasonToDateCoolingDD  0 non-null      float64
dtypes: float64(57), int64(6), object(27)
memory usage: 1.2+ MB

In [6]:
#Here is a final output that will be sufficient to see what coulumns to drop in comparison of the top few outputs we will drop columns in the next function.
df.agg('mean').head(60)

ELEVATION                           1650.200000
LATITUDE                              39.832800
LONGITUDE                           -104.657500
HOURLYWETBULBTEMPF                    24.853541
HOURLYWETBULBTEMPC                    -3.966507
HOURLYDewPointTempF                   16.673469
HOURLYDewPointTempC                   -8.511885
HOURLYRelativeHumidity                63.340336
HOURLYWindGustSpeed                   31.938144
HOURLYStationPressure                 24.513313
HOURLYPressureTendency                 4.514577
HOURLYPressureChange                   0.003672
HOURLYSeaLevelPressure                29.977875
HOURLYAltimeterSetting                29.924174
DAILYAverageRelativeHumidity                NaN
DAILYAverageDewPointTemp                    NaN
DAILYAverageWetBulbTemp                     NaN
DAILYSunrise                         704.341905
DAILYSunset                         1696.424313
DAILYAverageStationPressure           24.514444
DAILYAverageSeaLevelPressure                NaN
DAILYAverageWindSpeed                  9.695455
DAILYSustainedWindSpeed               21.400000
DAILYSustainedWindDirection          188.666667
MonthlyMaximumTemp                    44.600000
MonthlyMinimumTemp                    19.500000
MonthlyMeanTemp                       32.100000
MonthlyAverageRH                            NaN
MonthlyDewpointTemp                         NaN
MonthlyWetBulbTemp                          NaN
MonthlyAvgHeatingDegreeDays                 NaN
MonthlyAvgCoolingDegreeDays                 NaN
MonthlyStationPressure                24.570000
MonthlySeaLevelPressure               30.040000
MonthlyAverageWindSpeed                     NaN
MonthlyDeptFromNormalMaximumTemp       0.600000
MonthlyDeptFromNormalMinimumTemp       2.100000
MonthlyDeptFromNormalAverageTemp       1.400000
MonthlyGreatestPrecip                       NaN
MonthlyGreatestPrecipDate                   NaN
MonthlyGreatestSnowfall                     NaN
MonthlyGreatestSnowfallDate                 NaN
MonthlyGreatestSnowDepth                    NaN
MonthlyGreatestSnowDepthDate                NaN
MonthlyDaysWithGT90Temp                0.000000
MonthlyDaysWithLT32Temp                6.000000
MonthlyDaysWithGT32Temp               29.000000
MonthlyDaysWithLT0Temp                 1.000000
MonthlyDaysWithGT001Precip                  NaN
MonthlyDaysWithGT010Precip                  NaN
MonthlyDaysWithGT1Snow                      NaN
MonthlyMaxSeaLevelPressureValue             NaN
MonthlyMaxSeaLevelPressureDate     -9999.000000
MonthlyMaxSeaLevelPressureTime     -9999.000000
MonthlyMinSeaLevelPressureValue             NaN
MonthlyMinSeaLevelPressureDate     -9999.000000
MonthlyMinSeaLevelPressureTime     -9999.000000
MonthlyTotalHeatingDegreeDays       1016.000000
MonthlyTotalCoolingDegreeDays          0.000000
MonthlyDeptFromNormalHeatingDD       -47.000000
dtype: float64

In [7]:
#dropping columns that are unnecessary & putting them into new df1
df1 = df.drop(columns=['DAILYAverageRelativeHumidity', 'DAILYAverageDewPointTemp', 'DAILYAverageWetBulbTemp', 'DAILYAverageSeaLevelPressure',
       'MonthlyAverageRH', 'MonthlyDewpointTemp', 'MonthlyWetBulbTemp', 'MonthlyAvgHeatingDegreeDays', 'MonthlyAvgCoolingDegreeDays',
       'MonthlyAverageWindSpeed', 'MonthlyGreatestPrecip', 'MonthlyGreatestPrecipDate', 'MonthlyGreatestSnowfall', 'MonthlyGreatestSnowfallDate',
       'MonthlyGreatestSnowDepth', 'MonthlyGreatestSnowDepthDate', 'MonthlyDaysWithGT001Precip', 'MonthlyDaysWithGT010Precip', 'MonthlyDaysWithGT1Snow', 
       'MonthlyMaxSeaLevelPressureValue', 'MonthlyMaxSeaLevelPressureDate', 'MonthlyMaxSeaLevelPressureTime', 'MonthlyMinSeaLevelPressureValue', 
       'MonthlyMinSeaLevelPressureDate', 'MonthlyMinSeaLevelPressureTime', 'MonthlyTotalCoolingDegreeDays', 'MonthlyDeptFromNormalCoolingDD', 'MonthlyTotalSeasonToDateHeatingDD',
       'MonthlyTotalSeasonToDateCoolingDD'])
df1

,STATION,STATION_NAME,ELEVATION,LATITUDE,LONGITUDE,DATE,REPORTTPYE,HOURLYSKYCONDITIONS,HOURLYVISIBILITY,HOURLYPRSENTWEATHERTYPE,...,MonthlyDeptFromNormalMinimumTemp,MonthlyDeptFromNormalAverageTemp,MonthlyDeptFromNormalPrecip,MonthlyTotalLiquidPrecip,MonthlyDaysWithGT90Temp,MonthlyDaysWithLT32Temp,MonthlyDaysWithGT32Temp,MonthlyDaysWithLT0Temp,MonthlyTotalHeatingDegreeDays,MonthlyDeptFromNormalHeatingDD
0,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 00:37,FM-16,SCT:04 9,7.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 00:46,FM-16,BKN:07 9 BKN:07 180,9.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 00:53,FM-15,BKN:07 9 BKN:07 180,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 01:05,FM-16,OVC:08 10,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 01:33,FM-16,BKN:07 9 BKN:07 180,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1706,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 21:53,FM-15,FEW:02 30 OVC:08 100,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1707,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 22:53,FM-15,FEW:02 30 OVC:08 90,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1708,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 23:00,FM-12,26,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1709,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 23:53,FM-15,FEW:02 20 OVC:08 110,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1710,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 23:59,SOD,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#We see a much cleaner dataset with all columns dropped that contained blanks or no relevant data
df1.describe()

,ELEVATION,LATITUDE,LONGITUDE,HOURLYWETBULBTEMPF,HOURLYWETBULBTEMPC,HOURLYDewPointTempF,HOURLYDewPointTempC,HOURLYRelativeHumidity,HOURLYWindGustSpeed,HOURLYStationPressure,...,MonthlySeaLevelPressure,MonthlyDeptFromNormalMaximumTemp,MonthlyDeptFromNormalMinimumTemp,MonthlyDeptFromNormalAverageTemp,MonthlyDaysWithGT90Temp,MonthlyDaysWithLT32Temp,MonthlyDaysWithGT32Temp,MonthlyDaysWithLT0Temp,MonthlyTotalHeatingDegreeDays,MonthlyDeptFromNormalHeatingDD
count,1.711000e+03,1.711000e+03,1.711000e+03,1666.000000,1666.000000,1666.000000,1666.000000,1666.000000,97.000000,1666.000000,...,1.00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,1.650200e+03,3.983280e+01,-1.046575e+02,24.853541,-3.966507,16.673469,-8.511885,63.340336,31.938144,24.513313,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
std,2.342634e-11,1.485468e-12,1.023481e-12,9.879766,5.465728,8.380600,4.656388,22.671277,7.549578,0.176896,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.650200e+03,3.983280e+01,-1.046575e+02,-10.000000,-23.600000,-14.000000,-25.600000,11.000000,16.000000,24.030000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
25%,1.650200e+03,3.983280e+01,-1.046575e+02,19.000000,-7.000000,12.000000,-11.100000,45.000000,28.000000,24.390000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
50%,1.650200e+03,3.983280e+01,-1.046575e+02,26.000000,-3.200000,18.000000,-7.800000,63.000000,31.000000,24.550000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
75%,1.650200e+03,3.983280e+01,-1.046575e+02,32.000000,0.100000,22.000000,-5.600000,85.000000,37.000000,24.640000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
max,1.650200e+03,3.983280e+01,-1.046575e+02,46.000000,7.700000,34.000000,1.100000,100.000000,54.000000,24.950000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0

In [9]:
#we now see clean data with no unnessary values for now that we need to address.
df1.agg('mean')

ELEVATION                           1650.200000
LATITUDE                              39.832800
LONGITUDE                           -104.657500
HOURLYWETBULBTEMPF                    24.853541
HOURLYWETBULBTEMPC                    -3.966507
HOURLYDewPointTempF                   16.673469
HOURLYDewPointTempC                   -8.511885
HOURLYRelativeHumidity                63.340336
HOURLYWindGustSpeed                   31.938144
HOURLYStationPressure                 24.513313
HOURLYPressureTendency                 4.514577
HOURLYPressureChange                   0.003672
HOURLYSeaLevelPressure                29.977875
HOURLYAltimeterSetting                29.924174
DAILYSunrise                         704.341905
DAILYSunset                         1696.424313
DAILYAverageStationPressure           24.514444
DAILYAverageWindSpeed                  9.695455
DAILYSustainedWindSpeed               21.400000
DAILYSustainedWindDirection          188.666667
MonthlyMaximumTemp                    44.600000
MonthlyMinimumTemp                    19.500000
MonthlyMeanTemp                       32.100000
MonthlyStationPressure                24.570000
MonthlySeaLevelPressure               30.040000
MonthlyDeptFromNormalMaximumTemp       0.600000
MonthlyDeptFromNormalMinimumTemp       2.100000
MonthlyDeptFromNormalAverageTemp       1.400000
MonthlyDaysWithGT90Temp                0.000000
MonthlyDaysWithLT32Temp                6.000000
MonthlyDaysWithGT32Temp               29.000000
MonthlyDaysWithLT0Temp                 1.000000
MonthlyTotalHeatingDegreeDays       1016.000000
MonthlyDeptFromNormalHeatingDD       -47.000000
dtype: float64

## Set the date column as the index of the DataFrame

In [10]:
#setting 'Date' column type to datetime64[ns] 
df1['DATE'] = pd.to_datetime(df1['DATE'])
df1.info()
#we see success, we #5, DATE is now datetime64[ns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1711 entries, 0 to 1710
Data columns (total 61 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   STATION                           1711 non-null   object
 1   STATION_NAME                      1711 non-null   object
 2   ELEVATION                         1711 non-null   float64
 3   LATITUDE                          1711 non-null   float64
 4   LONGITUDE                         1711 non-null   float64
 5   DATE                              1711 non-null   datetime64[ns]
 6   REPORTTPYE                        1711 non-null   object
 7   HOURLYSKYCONDITIONS               1417 non-null   object
 8   HOURLYVISIBILITY                  1307 non-null   object
 9   HOURLYPRSENTWEATHERTYPE           350 non-null    object
 10  HOURLYDRYBULBTEMPF                1666 non-null   object
 11  HOURLYDRYBULBTEMPC                1666 non-null   object
 12  HOURLYWETBULBTEMPF                1666 non-null   float64
 13  HOURLYWETBULBTEMPC                1666 non-null   float64
 14  HOURLYDewPointTempF               1666 non-null   float64
 15  HOURLYDewPointTempC               1666 non-null   float64
 16  HOURLYRelativeHumidity            1666 non-null   float64
 17  HOURLYWindSpeed                   1666 non-null   object
 18  HOURLYWindDirection               1664 non-null   object
 19  HOURLYWindGustSpeed               97 non-null     float64
 20  HOURLYStationPressure             1666 non-null   float64
 21  HOURLYPressureTendency            686 non-null    float64
 22  HOURLYPressureChange              354 non-null    float64
 23  HOURLYSeaLevelPressure            1440 non-null   float64
 24  HOURLYPrecip                      1198 non-null   object
 25  HOURLYAltimeterSetting            1308 non-null   float64
 26  DAILYMaximumDryBulbTemp           180 non-null    object
 27  DAILYMinimumDryBulbTemp           180 non-null    object
 28  DAILYAverageDryBulbTemp           180 non-null    object
 29  DAILYDeptFromNormalAverageTemp    180 non-null    object
 30  DAILYHeatingDegreeDays            180 non-null    object
 31  DAILYCoolingDegreeDays            180 non-null    object
 32  DAILYSunrise                      1711 non-null   int64
 33  DAILYSunset                       1711 non-null   int64
 34  DAILYWeather                      15 non-null     object
 35  DAILYPrecip                       61 non-null     object
 36  DAILYSnowfall                     45 non-null     object
 37  DAILYSnowDepth                    45 non-null     object
 38  DAILYAverageStationPressure       45 non-null     float64
 39  DAILYAverageWindSpeed             44 non-null     float64
 40  DAILYPeakWindSpeed                45 non-null     object
 41  PeakWindDirection                 45 non-null     object
 42  DAILYSustainedWindSpeed           45 non-null     float64
 43  DAILYSustainedWindDirection       45 non-null     float64
 44  MonthlyMaximumTemp                1 non-null      float64
 45  MonthlyMinimumTemp                1 non-null      float64
 46  MonthlyMeanTemp                   1 non-null      float64
 47  MonthlyStationPressure            1 non-null      float64
 48  MonthlySeaLevelPressure           1 non-null      float64
 49  MonthlyTotalSnowfall              11 non-null     object
 50  MonthlyDeptFromNormalMaximumTemp  1 non-null      float64
 51  MonthlyDeptFromNormalMinimumTemp  1 non-null      float64
 52  MonthlyDeptFromNormalAverageTemp  1 non-null      float64
 53  MonthlyDeptFromNormalPrecip       1 non-null      object
 54  MonthlyTotalLiquidPrecip          1 non-null      object
 55  MonthlyDaysWithGT90Temp           1 non-null      float64
 56  MonthlyDaysWithLT32Temp           1 non-null      float64
 57  MonthlyDaysWithGT32Temp           1 non-null      float64
 58  MonthlyDaysWithLT0Temp            1 non-null      float64
 59  MonthlyTotalHeatingDegreeDays     1 non-null      float64
 60  MonthlyDeptFromNormalHeatingDD    1 non-null      float64
dtypes: datetime64[ns](1), float64(32), int64(2), object(26)
memory usage: 815.5+ KB

## Create an "Elapsed Time" column that shows the amount of time since the first observation. & Format the "Elapsed Time" column into some easily-readable form. For example, after two hours, the column should NOT read 7200.

In [11]:
#importing datetime 
from datetime import datetime

In [12]:
#adding new column Elasped Time. Right now, this is a copy of DATE column. We will manipulate this to represent duration in the next few functions to clean this
df1['Elapsed Time'] = df1['DATE']
df1

,STATION,STATION_NAME,ELEVATION,LATITUDE,LONGITUDE,DATE,REPORTTPYE,HOURLYSKYCONDITIONS,HOURLYVISIBILITY,HOURLYPRSENTWEATHERTYPE,...,MonthlyDeptFromNormalAverageTemp,MonthlyDeptFromNormalPrecip,MonthlyTotalLiquidPrecip,MonthlyDaysWithGT90Temp,MonthlyDaysWithLT32Temp,MonthlyDaysWithGT32Temp,MonthlyDaysWithLT0Temp,MonthlyTotalHeatingDegreeDays,MonthlyDeptFromNormalHeatingDD,Elapsed Time
0,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 00:37:00,FM-16,SCT:04 9,7.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01 00:37:00
1,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 00:46:00,FM-16,BKN:07 9 BKN:07 180,9.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01 00:46:00
2,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 00:53:00,FM-15,BKN:07 9 BKN:07 180,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01 00:53:00
3,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 01:05:00,FM-16,OVC:08 10,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01 01:05:00
4,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 01:33:00,FM-16,BKN:07 9 BKN:07 180,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01 01:33:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1706,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 21:53:00,FM-15,FEW:02 30 OVC:08 100,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-14 21:53:00
1707,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 22:53:00,FM-15,FEW:02 30 OVC:08 90,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-14 22:53:00
1708,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 23:00:00,FM-12,26,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-14 23:00:00
1709,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 23:53:00,FM-15,FEW:02 20 OVC:08 110,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-14 23:53:00
1710,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 23:59:00,SOD,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-14 23:59:00

checking different formatting options with the time for the 'Elapsed Time'

In [13]:
#year
et = df1['Elapsed Time']
et.dt.year

0       2019
1       2019
2       2019
3       2019
4       2019
        ...
1706    2019
1707    2019
1708    2019
1709    2019
1710    2019
Name: Elapsed Time, Length: 1711, dtype: int64

In [14]:
##time/duration
et = df1['Elapsed Time']
et.dt.time
#this is the true reprecentation of the duration in 'time' form. We will use this

0       00:37:00
1       00:46:00
2       00:53:00
3       01:05:00
4       01:33:00
          ...
1706    21:53:00
1707    22:53:00
1708    23:00:00
1709    23:53:00
1710    23:59:00
Name: Elapsed Time, Length: 1711, dtype: object

In [15]:
#hour
et = df1['Elapsed Time']
et.dt.hour

0        0
1        0
2        0
3        1
4        1
        ..
1706    21
1707    22
1708    23
1709    23
1710    23
Name: Elapsed Time, Length: 1711, dtype: int64

In [16]:
#CHanging the 'Elapsed Time' column to represent time since first observation
df1['Elapsed Time'] = et.dt.time
df1

,STATION,STATION_NAME,ELEVATION,LATITUDE,LONGITUDE,DATE,REPORTTPYE,HOURLYSKYCONDITIONS,HOURLYVISIBILITY,HOURLYPRSENTWEATHERTYPE,...,MonthlyDeptFromNormalAverageTemp,MonthlyDeptFromNormalPrecip,MonthlyTotalLiquidPrecip,MonthlyDaysWithGT90Temp,MonthlyDaysWithLT32Temp,MonthlyDaysWithGT32Temp,MonthlyDaysWithLT0Temp,MonthlyTotalHeatingDegreeDays,MonthlyDeptFromNormalHeatingDD,Elapsed Time
0,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 00:37:00,FM-16,SCT:04 9,7.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:37:00
1,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 00:46:00,FM-16,BKN:07 9 BKN:07 180,9.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:46:00
2,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 00:53:00,FM-15,BKN:07 9 BKN:07 180,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:53:00
3,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 01:05:00,FM-16,OVC:08 10,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01:05:00
4,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-01-01 01:33:00,FM-16,BKN:07 9 BKN:07 180,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01:33:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1706,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 21:53:00,FM-15,FEW:02 30 OVC:08 100,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21:53:00
1707,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 22:53:00,FM-15,FEW:02 30 OVC:08 90,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22:53:00
1708,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 23:00:00,FM-12,26,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23:00:00
1709,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 23:53:00,FM-15,FEW:02 20 OVC:08 110,10.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23:53:00
1710,WBAN:03017,DENVER INTERNATIONAL AIRPORT CO US,1650.2,39.8328,-104.6575,2019-02-14 23:59:00,SOD,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23:59:00

##  Do all the things we've already been doing -- format the headings, deal with missing values, etc.

In [17]:
#describing the data for insight potentially
df1.describe()

,ELEVATION,LATITUDE,LONGITUDE,HOURLYWETBULBTEMPF,HOURLYWETBULBTEMPC,HOURLYDewPointTempF,HOURLYDewPointTempC,HOURLYRelativeHumidity,HOURLYWindGustSpeed,HOURLYStationPressure,...,MonthlySeaLevelPressure,MonthlyDeptFromNormalMaximumTemp,MonthlyDeptFromNormalMinimumTemp,MonthlyDeptFromNormalAverageTemp,MonthlyDaysWithGT90Temp,MonthlyDaysWithLT32Temp,MonthlyDaysWithGT32Temp,MonthlyDaysWithLT0Temp,MonthlyTotalHeatingDegreeDays,MonthlyDeptFromNormalHeatingDD
count,1.711000e+03,1.711000e+03,1.711000e+03,1666.000000,1666.000000,1666.000000,1666.000000,1666.000000,97.000000,1666.000000,...,1.00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,1.650200e+03,3.983280e+01,-1.046575e+02,24.853541,-3.966507,16.673469,-8.511885,63.340336,31.938144,24.513313,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
std,2.342634e-11,1.485468e-12,1.023481e-12,9.879766,5.465728,8.380600,4.656388,22.671277,7.549578,0.176896,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.650200e+03,3.983280e+01,-1.046575e+02,-10.000000,-23.600000,-14.000000,-25.600000,11.000000,16.000000,24.030000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
25%,1.650200e+03,3.983280e+01,-1.046575e+02,19.000000,-7.000000,12.000000,-11.100000,45.000000,28.000000,24.390000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
50%,1.650200e+03,3.983280e+01,-1.046575e+02,26.000000,-3.200000,18.000000,-7.800000,63.000000,31.000000,24.550000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
75%,1.650200e+03,3.983280e+01,-1.046575e+02,32.000000,0.100000,22.000000,-5.600000,85.000000,37.000000,24.640000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
max,1.650200e+03,3.983280e+01,-1.046575e+02,46.000000,7.700000,34.000000,1.100000,100.000000,54.000000,24.950000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0

In [18]:
#This is the only one we are able to run on page 178 due to the type of dataset we have. After running this function, we can confirm we have no missing values in the dataset to be of concern.
null_vec = pd.isnull(df1)
null_count = np.sum(null_vec)
null_count.head(10)

STATION                       0
STATION_NAME                  0
ELEVATION                     0
LATITUDE                      0
LONGITUDE                     0
DATE                          0
REPORTTPYE                    0
HOURLYSKYCONDITIONS         294
HOURLYVISIBILITY            404
HOURLYPRSENTWEATHERTYPE    1361
dtype: int64

these two essentially perform the same task in this dataset

In [19]:
#sum of 'NaN's' by column 
df1.isna().sum().head(10)
#since the program will be able to read NaN and 0s as the same, we will not need to change these values. We see no missing values in the first 8 columns that will identify each row as an individual line of information, therfore we will not interfer with this data any further and will contiue to analysis

STATION                       0
STATION_NAME                  0
ELEVATION                     0
LATITUDE                      0
LONGITUDE                     0
DATE                          0
REPORTTPYE                    0
HOURLYSKYCONDITIONS         294
HOURLYVISIBILITY            404
HOURLYPRSENTWEATHERTYPE    1361
dtype: int64

We see many values with 'NaN's to describe the variables with 'missing data'. Since they do not interfere with the intergers and could be used for further analysis, we will not make any changes to the NaN values. It would be best to leave them be for now until more insight is learned from the dataset. Replacing them with 0's could mess with the values of intetrger calculations, so we will not tamper with this data for now. We have the dataset cleaned sufficiently to be able to progress into some cool analysis.

## Perform analysis with the tools we've looked at so far. Keep in mind that the data may have to be grouped to be meaningful (average temp per day may be more useful than average for the whole two weeks, for example). Justify your analysis choices.

In [20]:
#mean of the dataframe by variable
df1.agg('mean')

ELEVATION                           1650.200000
LATITUDE                              39.832800
LONGITUDE                           -104.657500
HOURLYWETBULBTEMPF                    24.853541
HOURLYWETBULBTEMPC                    -3.966507
HOURLYDewPointTempF                   16.673469
HOURLYDewPointTempC                   -8.511885
HOURLYRelativeHumidity                63.340336
HOURLYWindGustSpeed                   31.938144
HOURLYStationPressure                 24.513313
HOURLYPressureTendency                 4.514577
HOURLYPressureChange                   0.003672
HOURLYSeaLevelPressure                29.977875
HOURLYAltimeterSetting                29.924174
DAILYSunrise                         704.341905
DAILYSunset                         1696.424313
DAILYAverageStationPressure           24.514444
DAILYAverageWindSpeed                  9.695455
DAILYSustainedWindSpeed               21.400000
DAILYSustainedWindDirection          188.666667
MonthlyMaximumTemp                    44.600000
MonthlyMinimumTemp                    19.500000
MonthlyMeanTemp                       32.100000
MonthlyStationPressure                24.570000
MonthlySeaLevelPressure               30.040000
MonthlyDeptFromNormalMaximumTemp       0.600000
MonthlyDeptFromNormalMinimumTemp       2.100000
MonthlyDeptFromNormalAverageTemp       1.400000
MonthlyDaysWithGT90Temp                0.000000
MonthlyDaysWithLT32Temp                6.000000
MonthlyDaysWithGT32Temp               29.000000
MonthlyDaysWithLT0Temp                 1.000000
MonthlyTotalHeatingDegreeDays       1016.000000
MonthlyDeptFromNormalHeatingDD       -47.000000
dtype: float64

In [21]:
#median of the dataframe by variable
df1.agg('median')

ELEVATION                           1650.2000
LATITUDE                              39.8328
LONGITUDE                           -104.6575
HOURLYWETBULBTEMPF                    26.0000
HOURLYWETBULBTEMPC                    -3.2000
HOURLYDewPointTempF                   18.0000
HOURLYDewPointTempC                   -7.8000
HOURLYRelativeHumidity                63.0000
HOURLYWindGustSpeed                   31.0000
HOURLYStationPressure                 24.5500
HOURLYPressureTendency                 5.0000
HOURLYPressureChange                   0.0100
HOURLYSeaLevelPressure                30.0050
HOURLYAltimeterSetting                29.9700
DAILYSunrise                         714.0000
DAILYSunset                         1709.0000
DAILYAverageStationPressure           24.5300
DAILYAverageWindSpeed                  9.5500
DAILYSustainedWindSpeed               18.0000
DAILYSustainedWindDirection          210.0000
MonthlyMaximumTemp                    44.6000
MonthlyMinimumTemp                    19.5000
MonthlyMeanTemp                       32.1000
MonthlyStationPressure                24.5700
MonthlySeaLevelPressure               30.0400
MonthlyDeptFromNormalMaximumTemp       0.6000
MonthlyDeptFromNormalMinimumTemp       2.1000
MonthlyDeptFromNormalAverageTemp       1.4000
MonthlyDaysWithGT90Temp                0.0000
MonthlyDaysWithLT32Temp                6.0000
MonthlyDaysWithGT32Temp               29.0000
MonthlyDaysWithLT0Temp                 1.0000
MonthlyTotalHeatingDegreeDays       1016.0000
MonthlyDeptFromNormalHeatingDD       -47.0000
dtype: float64

In [22]:
#describing the dataframe
df1.describe()

,ELEVATION,LATITUDE,LONGITUDE,HOURLYWETBULBTEMPF,HOURLYWETBULBTEMPC,HOURLYDewPointTempF,HOURLYDewPointTempC,HOURLYRelativeHumidity,HOURLYWindGustSpeed,HOURLYStationPressure,...,MonthlySeaLevelPressure,MonthlyDeptFromNormalMaximumTemp,MonthlyDeptFromNormalMinimumTemp,MonthlyDeptFromNormalAverageTemp,MonthlyDaysWithGT90Temp,MonthlyDaysWithLT32Temp,MonthlyDaysWithGT32Temp,MonthlyDaysWithLT0Temp,MonthlyTotalHeatingDegreeDays,MonthlyDeptFromNormalHeatingDD
count,1.711000e+03,1.711000e+03,1.711000e+03,1666.000000,1666.000000,1666.000000,1666.000000,1666.000000,97.000000,1666.000000,...,1.00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,1.650200e+03,3.983280e+01,-1.046575e+02,24.853541,-3.966507,16.673469,-8.511885,63.340336,31.938144,24.513313,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
std,2.342634e-11,1.485468e-12,1.023481e-12,9.879766,5.465728,8.380600,4.656388,22.671277,7.549578,0.176896,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.650200e+03,3.983280e+01,-1.046575e+02,-10.000000,-23.600000,-14.000000,-25.600000,11.000000,16.000000,24.030000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
25%,1.650200e+03,3.983280e+01,-1.046575e+02,19.000000,-7.000000,12.000000,-11.100000,45.000000,28.000000,24.390000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
50%,1.650200e+03,3.983280e+01,-1.046575e+02,26.000000,-3.200000,18.000000,-7.800000,63.000000,31.000000,24.550000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
75%,1.650200e+03,3.983280e+01,-1.046575e+02,32.000000,0.100000,22.000000,-5.600000,85.000000,37.000000,24.640000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0
max,1.650200e+03,3.983280e+01,-1.046575e+02,46.000000,7.700000,34.000000,1.100000,100.000000,54.000000,24.950000,...,30.04,0.6,2.1,1.4,0.0,6.0,29.0,1.0,1016.0,-47.0

In [23]:
#quick view of columns to see what we should groupby and aggregate for deeper dive
df1.columns

Index(['STATION', 'STATION_NAME', 'ELEVATION', 'LATITUDE', 'LONGITUDE', 'DATE',
       'REPORTTPYE', 'HOURLYSKYCONDITIONS', 'HOURLYVISIBILITY',
       'HOURLYPRSENTWEATHERTYPE', 'HOURLYDRYBULBTEMPF', 'HOURLYDRYBULBTEMPC',
       'HOURLYWETBULBTEMPF', 'HOURLYWETBULBTEMPC', 'HOURLYDewPointTempF',
       'HOURLYDewPointTempC', 'HOURLYRelativeHumidity', 'HOURLYWindSpeed',
       'HOURLYWindDirection', 'HOURLYWindGustSpeed', 'HOURLYStationPressure',
       'HOURLYPressureTendency', 'HOURLYPressureChange',
       'HOURLYSeaLevelPressure', 'HOURLYPrecip', 'HOURLYAltimeterSetting',
       'DAILYMaximumDryBulbTemp', 'DAILYMinimumDryBulbTemp',
       'DAILYAverageDryBulbTemp', 'DAILYDeptFromNormalAverageTemp',
       'DAILYHeatingDegreeDays', 'DAILYCoolingDegreeDays', 'DAILYSunrise',
       'DAILYSunset', 'DAILYWeather', 'DAILYPrecip', 'DAILYSnowfall',
       'DAILYSnowDepth', 'DAILYAverageStationPressure',
       'DAILYAverageWindSpeed', 'DAILYPeakWindSpeed', 'PeakWindDirection',
       'DAILYSustainedWindSpeed', 'DAILYSustainedWindDirection',
       'MonthlyMaximumTemp', 'MonthlyMinimumTemp', 'MonthlyMeanTemp',
       'MonthlyStationPressure', 'MonthlySeaLevelPressure',
       'MonthlyTotalSnowfall', 'MonthlyDeptFromNormalMaximumTemp',
       'MonthlyDeptFromNormalMinimumTemp', 'MonthlyDeptFromNormalAverageTemp',
       'MonthlyDeptFromNormalPrecip', 'MonthlyTotalLiquidPrecip',
       'MonthlyDaysWithGT90Temp', 'MonthlyDaysWithLT32Temp',
       'MonthlyDaysWithGT32Temp', 'MonthlyDaysWithLT0Temp',
       'MonthlyTotalHeatingDegreeDays', 'MonthlyDeptFromNormalHeatingDD',
       'Elapsed Time'],
      dtype='object')

In [24]:
#describing by groupby 'REPORT TYPE' - this has 4 distinct categories
df1.groupby('REPORTTPYE').describe()

           ELEVATION                                                        \
               count    mean           std     min     25%     50%     75%
REPORTTPYE
FM-12          360.0  1650.2  1.593831e-12  1650.2  1650.2  1650.2  1650.2
FM-15         1080.0  1650.2  3.048219e-11  1650.2  1650.2  1650.2  1650.2
FM-16          226.0  1650.2  6.608473e-12  1650.2  1650.2  1650.2  1650.2
SOD             45.0  1650.2  1.379658e-12  1650.2  1650.2  1650.2  1650.2

                   LATITUDE           ... MonthlyTotalHeatingDegreeDays  \
               max    count     mean  ...                           75%
REPORTTPYE                            ...
FM-12       1650.2    360.0  39.8328  ...                           NaN
FM-15       1650.2   1080.0  39.8328  ...                           NaN
FM-16       1650.2    226.0  39.8328  ...                           NaN
SOD         1650.2     45.0  39.8328  ...                        1016.0

                   MonthlyDeptFromNormalHeatingDD                              \
               max                          count  mean std   min   25%   50%
REPORTTPYE
FM-12          NaN                            0.0   NaN NaN   NaN   NaN   NaN
FM-15          NaN                            0.0   NaN NaN   NaN   NaN   NaN
FM-16          NaN                            0.0   NaN NaN   NaN   NaN   NaN
SOD         1016.0                            1.0 -47.0 NaN -47.0 -47.0 -47.0


             75%   max
REPORTTPYE
FM-12        NaN   NaN
FM-15        NaN   NaN
FM-16        NaN   NaN
SOD        -47.0 -47.0

[4 rows x 272 columns]

In [25]:
# groupby median of 'REPORT TYPE' and 'HOURLYSKYCONDITIONS' - we can see a solid groupby for deeper analysis 
df1.groupby(['REPORTTPYE', 'HOURLYSKYCONDITIONS']).median()

                                ELEVATION  LATITUDE  LONGITUDE  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                       1650.2   39.8328  -104.6575
           15                      1650.2   39.8328  -104.6575
           2                       1650.2   39.8328  -104.6575
           26                      1650.2   39.8328  -104.6575
           41                      1650.2   39.8328  -104.6575
...                                   ...       ...        ...
FM-16      VV:09 16                1650.2   39.8328  -104.6575
           VV:09 2                 1650.2   39.8328  -104.6575
           VV:09 6                 1650.2   39.8328  -104.6575
           VV:09 7                 1650.2   39.8328  -104.6575
           VV:09 9                 1650.2   39.8328  -104.6575

                                HOURLYWETBULBTEMPF  HOURLYWETBULBTEMPC  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                  14.0               -9.90
           15                                 22.0               -5.55
           2                                  19.0               -7.00
           26                                 22.0               -5.60
           41                                 25.5               -3.60
...                                            ...                 ...
FM-16      VV:09 16                           20.0               -6.80
           VV:09 2                            17.0               -8.10
           VV:09 6                            15.0               -9.40
           VV:09 7                            17.0               -8.20
           VV:09 9                            23.0               -4.85

                                HOURLYDewPointTempF  HOURLYDewPointTempC  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                   12.0               -11.10
           15                                  20.0                -6.70
           2                                   18.0                -7.80
           26                                  14.0               -10.00
           41                                  18.0                -7.75
...                                             ...                  ...
FM-16      VV:09 16                            15.0                -9.40
           VV:09 2                             16.0                -8.90
           VV:09 6                             13.0               -10.60
           VV:09 7                             15.5                -9.20
           VV:09 9                             22.0                -5.55

                                HOURLYRelativeHumidity  HOURLYWindGustSpeed  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                      88.0                  NaN
           15                                     88.0                  NaN
           2                                      96.0                  NaN
           26                                     75.0                  NaN
           41                                     74.0                  NaN
...                                                ...                  ...
FM-16      VV:09 16                               75.0                 21.0
           VV:09 2                                93.0                 25.0
           VV:09 6                                88.0                  NaN
           VV:09 7                                90.0                 29.0
           VV:09 9                                92.0                 30.0

                                HOURLYStationPressure  ...  \
REPORTTPYE HOURLYSKYCONDITIONS                         ...
FM-12      1                                   24.230  ...
           15                                  24.615  ...
           2                                   24.370  ...
           26                                  24.600  ...
           41                                  24.685  ...
...                                               ...  ...
FM-16      VV:09 16                            24.750  ...
           VV:09 2                             24.210  ...
           VV:09 6                             24.270  ...
           VV:09 7                             24.480  ...
           VV:09 9                             24.620  ...

                                MonthlySeaLevelPressure  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                        NaN
           15                                       NaN
           2                                        NaN
           26                                       NaN
           41                                       NaN
...                                                 ...
FM-16      VV:09 16                                 NaN
           VV:09 2                                  NaN
           VV:09 6                                  NaN
           VV:09 7                                  NaN
           VV:09 9                                  NaN

                                MonthlyDeptFromNormalMaximumTemp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                                 NaN
           15                                                NaN
           2                                                 NaN
           26                                                NaN
           41                                                NaN
...                                                          ...
FM-16      VV:09 16                                          NaN
           VV:09 2                                           NaN
           VV:09 6                                           NaN
           VV:09 7                                           NaN
           VV:09 9                                           NaN

                                MonthlyDeptFromNormalMinimumTemp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                                 NaN
           15                                                NaN
           2                                                 NaN
           26                                                NaN
           41                                                NaN
...                                                          ...
FM-16      VV:09 16                                          NaN
           VV:09 2                                           NaN
           VV:09 6                                           NaN
           VV:09 7                                           NaN
           VV:09 9                                           NaN

                                MonthlyDeptFromNormalAverageTemp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                                 NaN
           15                                                NaN
           2                                                 NaN
           26                                                NaN
           41                                                NaN
...                                                          ...
FM-16      VV:09 16                                          NaN
           VV:09 2                                           NaN
           VV:09 6                                           NaN
           VV:09 7                                           NaN
           VV:09 9                                           NaN

                                MonthlyDaysWithGT90Temp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                        NaN
           15                                       NaN
           2                                        NaN
           26                                       NaN
           41                                       NaN
...                                                 ...
FM-16      VV:09 16                                 NaN
           VV:09 2                                  NaN
           VV:09 6                                  NaN
           VV:09 7                                  NaN
           VV:09 9                                  NaN

                                MonthlyDaysWithLT32Temp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                        NaN
           15                                       NaN
           2                                        NaN
           26                                       NaN
           41                                       NaN
...                                                 ...
FM-16      VV:09 16                                 NaN
           VV:09 2                                  NaN
           VV:09 6                                  NaN
           VV:09 7                                  NaN
           VV:09 9                                  NaN

                                MonthlyDaysWithGT32Temp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                        NaN
           15                                       NaN
           2                                        NaN
           26                                       NaN
           41                                       NaN
...                                                 ...
FM-16      VV:09 16                                 NaN
           VV:09 2                                  NaN
           VV:09 6                                  NaN
           VV:09 7                                  NaN
           VV:09 9                                  NaN

                                MonthlyDaysWithLT0Temp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                       NaN
           15                                      NaN
           2                                       NaN
           26                                      NaN
           41                                      NaN
...                                                ...
FM-16      VV:09 16                                NaN
           VV:09 2                                 NaN
           VV:09 6                                 NaN
           VV:09 7                                 NaN
           VV:09 9                                 NaN

                                MonthlyTotalHeatingDegreeDays  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                              NaN
           15                                             NaN
           2                                              NaN
           26                                             NaN
           41                                             NaN
...                                                       ...
FM-16      VV:09 16                                       NaN
           VV:09 2                                        NaN
           VV:09 6                                        NaN
           VV:09 7                                        NaN
           VV:09 9                                        NaN

                                MonthlyDeptFromNormalHeatingDD
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                               NaN
           15                                              NaN
           2                                               NaN
           26                                              NaN
           41                                              NaN
...                                                        ...
FM-16      VV:09 16                                        NaN
           VV:09 2                                         NaN
           VV:09 6                                         NaN
           VV:09 7                                         NaN
           VV:09 9                                         NaN

[546 rows x 34 columns]

In [26]:
# groupby mean of 'REPORT TYPE' and 'HOURLYSKYCONDITIONS' - we can see a solid groupby for deeper analysis 
df1.groupby(['REPORTTPYE', 'HOURLYSKYCONDITIONS']).mean()

                                ELEVATION  LATITUDE  LONGITUDE  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                       1650.2   39.8328  -104.6575
           15                      1650.2   39.8328  -104.6575
           2                       1650.2   39.8328  -104.6575
           26                      1650.2   39.8328  -104.6575
           41                      1650.2   39.8328  -104.6575
...                                   ...       ...        ...
FM-16      VV:09 16                1650.2   39.8328  -104.6575
           VV:09 2                 1650.2   39.8328  -104.6575
           VV:09 6                 1650.2   39.8328  -104.6575
           VV:09 7                 1650.2   39.8328  -104.6575
           VV:09 9                 1650.2   39.8328  -104.6575

                                HOURLYWETBULBTEMPF  HOURLYWETBULBTEMPC  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                             14.000000           -9.900000
           15                            21.166667           -5.966667
           2                             22.533333           -5.273333
           26                            17.705882           -7.917647
           41                            21.333333           -5.916667
...                                            ...                 ...
FM-16      VV:09 16                      20.000000           -6.800000
           VV:09 2                       16.238095           -8.680952
           VV:09 6                       15.000000           -9.400000
           VV:09 7                       17.000000           -8.200000
           VV:09 9                       23.000000           -4.850000

                                HOURLYDewPointTempF  HOURLYDewPointTempC  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                              12.000000           -11.100000
           15                             17.833333            -7.866667
           2                              21.466667            -5.840000
           26                             11.647059           -11.311765
           41                             15.666667            -9.066667
...                                             ...                  ...
FM-16      VV:09 16                       15.000000            -9.400000
           VV:09 2                        15.476190            -9.195238
           VV:09 6                        13.000000           -10.600000
           VV:09 7                        15.500000            -9.200000
           VV:09 9                        22.000000            -5.550000

                                HOURLYRelativeHumidity  HOURLYWindGustSpeed  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                 88.000000                  NaN
           15                                81.583333                  NaN
           2                                 93.866667                  NaN
           26                                71.882353                  NaN
           41                                71.333333                  NaN
...                                                ...                  ...
FM-16      VV:09 16                          75.000000                 21.0
           VV:09 2                           94.809524                 25.0
           VV:09 6                           88.000000                  NaN
           VV:09 7                           90.000000                 29.0
           VV:09 9                           92.000000                 30.0

                                HOURLYStationPressure  ...  \
REPORTTPYE HOURLYSKYCONDITIONS                         ...
FM-12      1                                24.230000  ...
           15                               24.558333  ...
           2                                24.438667  ...
           26                               24.599412  ...
           41                               24.691667  ...
...                                               ...  ...
FM-16      VV:09 16                         24.750000  ...
           VV:09 2                          24.225714  ...
           VV:09 6                          24.270000  ...
           VV:09 7                          24.480000  ...
           VV:09 9                          24.620000  ...

                                MonthlySeaLevelPressure  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                        NaN
           15                                       NaN
           2                                        NaN
           26                                       NaN
           41                                       NaN
...                                                 ...
FM-16      VV:09 16                                 NaN
           VV:09 2                                  NaN
           VV:09 6                                  NaN
           VV:09 7                                  NaN
           VV:09 9                                  NaN

                                MonthlyDeptFromNormalMaximumTemp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                                 NaN
           15                                                NaN
           2                                                 NaN
           26                                                NaN
           41                                                NaN
...                                                          ...
FM-16      VV:09 16                                          NaN
           VV:09 2                                           NaN
           VV:09 6                                           NaN
           VV:09 7                                           NaN
           VV:09 9                                           NaN

                                MonthlyDeptFromNormalMinimumTemp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                                 NaN
           15                                                NaN
           2                                                 NaN
           26                                                NaN
           41                                                NaN
...                                                          ...
FM-16      VV:09 16                                          NaN
           VV:09 2                                           NaN
           VV:09 6                                           NaN
           VV:09 7                                           NaN
           VV:09 9                                           NaN

                                MonthlyDeptFromNormalAverageTemp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                                 NaN
           15                                                NaN
           2                                                 NaN
           26                                                NaN
           41                                                NaN
...                                                          ...
FM-16      VV:09 16                                          NaN
           VV:09 2                                           NaN
           VV:09 6                                           NaN
           VV:09 7                                           NaN
           VV:09 9                                           NaN

                                MonthlyDaysWithGT90Temp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                        NaN
           15                                       NaN
           2                                        NaN
           26                                       NaN
           41                                       NaN
...                                                 ...
FM-16      VV:09 16                                 NaN
           VV:09 2                                  NaN
           VV:09 6                                  NaN
           VV:09 7                                  NaN
           VV:09 9                                  NaN

                                MonthlyDaysWithLT32Temp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                        NaN
           15                                       NaN
           2                                        NaN
           26                                       NaN
           41                                       NaN
...                                                 ...
FM-16      VV:09 16                                 NaN
           VV:09 2                                  NaN
           VV:09 6                                  NaN
           VV:09 7                                  NaN
           VV:09 9                                  NaN

                                MonthlyDaysWithGT32Temp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                        NaN
           15                                       NaN
           2                                        NaN
           26                                       NaN
           41                                       NaN
...                                                 ...
FM-16      VV:09 16                                 NaN
           VV:09 2                                  NaN
           VV:09 6                                  NaN
           VV:09 7                                  NaN
           VV:09 9                                  NaN

                                MonthlyDaysWithLT0Temp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                       NaN
           15                                      NaN
           2                                       NaN
           26                                      NaN
           41                                      NaN
...                                                ...
FM-16      VV:09 16                                NaN
           VV:09 2                                 NaN
           VV:09 6                                 NaN
           VV:09 7                                 NaN
           VV:09 9                                 NaN

                                MonthlyTotalHeatingDegreeDays  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                              NaN
           15                                             NaN
           2                                              NaN
           26                                             NaN
           41                                             NaN
...                                                       ...
FM-16      VV:09 16                                       NaN
           VV:09 2                                        NaN
           VV:09 6                                        NaN
           VV:09 7                                        NaN
           VV:09 9                                        NaN

                                MonthlyDeptFromNormalHeatingDD
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                               NaN
           15                                              NaN
           2                                               NaN
           26                                              NaN
           41                                              NaN
...                                                        ...
FM-16      VV:09 16                                        NaN
           VV:09 2                                         NaN
           VV:09 6                                         NaN
           VV:09 7                                         NaN
           VV:09 9                                         NaN

[546 rows x 34 columns]

In [27]:
# groupby count of 'REPORT TYPE' and 'HOURLYSKYCONDITIONS' -- using count quicky can show how frequently each station reports various
# skyconditions by various report type -- this provides a unique perspective of the data as well as collection methods
df1.groupby(['REPORTTPYE', 'HOURLYSKYCONDITIONS']).count()

                                STATION  STATION_NAME  ELEVATION  LATITUDE  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                          1             1          1         1
           15                        12            12         12        12
           2                         15            15         15        15
           26                        17            17         17        17
           41                         6             6          6         6
...                                 ...           ...        ...       ...
FM-16      VV:09 16                   1             1          1         1
           VV:09 2                   21            21         21        21
           VV:09 6                    1             1          1         1
           VV:09 7                    2             2          2         2
           VV:09 9                    2             2          2         2

                                LONGITUDE  DATE  HOURLYVISIBILITY  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                            1     1                 0
           15                          12    12                 0
           2                           15    15                 1
           26                          17    17                 0
           41                           6     6                 0
...                                   ...   ...               ...
FM-16      VV:09 16                     1     1                 1
           VV:09 2                     21    21                21
           VV:09 6                      1     1                 1
           VV:09 7                      2     2                 2
           VV:09 9                      2     2                 2

                                HOURLYPRSENTWEATHERTYPE  HOURLYDRYBULBTEMPF  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                          0                   1
           15                                         0                  12
           2                                          5                  15
           26                                         1                  17
           41                                         0                   6
...                                                 ...                 ...
FM-16      VV:09 16                                   1                   1
           VV:09 2                                   21                  21
           VV:09 6                                    1                   1
           VV:09 7                                    2                   2
           VV:09 9                                    2                   2

                                HOURLYDRYBULBTEMPC  ...  \
REPORTTPYE HOURLYSKYCONDITIONS                      ...
FM-12      1                                     1  ...
           15                                   12  ...
           2                                    15  ...
           26                                   17  ...
           41                                    6  ...
...                                            ...  ...
FM-16      VV:09 16                              1  ...
           VV:09 2                              21  ...
           VV:09 6                               1  ...
           VV:09 7                               2  ...
           VV:09 9                               2  ...

                                MonthlyDeptFromNormalAverageTemp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                                   0
           15                                                  0
           2                                                   0
           26                                                  0
           41                                                  0
...                                                          ...
FM-16      VV:09 16                                            0
           VV:09 2                                             0
           VV:09 6                                             0
           VV:09 7                                             0
           VV:09 9                                             0

                                MonthlyDeptFromNormalPrecip  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                              0
           15                                             0
           2                                              0
           26                                             0
           41                                             0
...                                                     ...
FM-16      VV:09 16                                       0
           VV:09 2                                        0
           VV:09 6                                        0
           VV:09 7                                        0
           VV:09 9                                        0

                                MonthlyTotalLiquidPrecip  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                           0
           15                                          0
           2                                           0
           26                                          0
           41                                          0
...                                                  ...
FM-16      VV:09 16                                    0
           VV:09 2                                     0
           VV:09 6                                     0
           VV:09 7                                     0
           VV:09 9                                     0

                                MonthlyDaysWithGT90Temp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                          0
           15                                         0
           2                                          0
           26                                         0
           41                                         0
...                                                 ...
FM-16      VV:09 16                                   0
           VV:09 2                                    0
           VV:09 6                                    0
           VV:09 7                                    0
           VV:09 9                                    0

                                MonthlyDaysWithLT32Temp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                          0
           15                                         0
           2                                          0
           26                                         0
           41                                         0
...                                                 ...
FM-16      VV:09 16                                   0
           VV:09 2                                    0
           VV:09 6                                    0
           VV:09 7                                    0
           VV:09 9                                    0

                                MonthlyDaysWithGT32Temp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                          0
           15                                         0
           2                                          0
           26                                         0
           41                                         0
...                                                 ...
FM-16      VV:09 16                                   0
           VV:09 2                                    0
           VV:09 6                                    0
           VV:09 7                                    0
           VV:09 9                                    0

                                MonthlyDaysWithLT0Temp  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                         0
           15                                        0
           2                                         0
           26                                        0
           41                                        0
...                                                ...
FM-16      VV:09 16                                  0
           VV:09 2                                   0
           VV:09 6                                   0
           VV:09 7                                   0
           VV:09 9                                   0

                                MonthlyTotalHeatingDegreeDays  \
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                                0
           15                                               0
           2                                                0
           26                                               0
           41                                               0
...                                                       ...
FM-16      VV:09 16                                         0
           VV:09 2                                          0
           VV:09 6                                          0
           VV:09 7                                          0
           VV:09 9                                          0

                                MonthlyDeptFromNormalHeatingDD  Elapsed Time
REPORTTPYE HOURLYSKYCONDITIONS
FM-12      1                                                 0             1
           15                                                0            12
           2                                                 0            15
           26                                                0            17
           41                                                0             6
...                                                        ...           ...
FM-16      VV:09 16                                          0             1
           VV:09 2                                           0            21
           VV:09 6                                           0             1
           VV:09 7                                           0             2
           VV:09 9                                           0             2

[546 rows x 60 columns]

## Summary

We were succesfully able to load the dataset and use the correct functions to maipulate the dataset by dropping unnecessary columns, setting DATE column as index, create 'Elapsed time' column with proper format to represent time from first observation, deal with missing or NaN values, and perfrom analysis with meaningful groupby choices. We maipulated the dataset to transform it into a cleaner version to be able to allow new perspective by adding new columns and cleaning it up with formatting and other ways to handle the dataset to be able to run analysis. We succesfully we able to have meaningful groupby functions that could be used for further analysis if desired.

### Reference:
Chen, D. Y. (2019). Python Data Analysis. Pearson Addison Wesley Data & Analytics Series. In Pandas for Everyone.